---
- name: checking status
  shell: sudo systemctl status "{{ service }}"
  register: status
  ignore_errors: yes
- name: debugging
  debug:
    var: status.rc
- name: restart if stopped
  service: 
    name: "{{ service }}"
    state: restarted
  when: status.rc != 0
  register: restart
- name: debugging
  debug:
    var: restarted
